export enum Permission {
  // Users & Invites
  CREATE_INVITE = 'CREATE_INVITE',
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',

  // Topics & Questions
  MANAGE_TOPICS = 'MANAGE_TOPICS',
  CREATE_QUESTION = 'CREATE_QUESTION',
  EDIT_QUESTION = 'EDIT_QUESTION',
  DELETE_QUESTION = 'DELETE_QUESTION',
  BULK_UPLOAD_QUESTIONS = 'BULK_UPLOAD_QUESTIONS',

  // Exams
  CREATE_EXAM = 'CREATE_EXAM',
  EDIT_EXAM = 'EDIT_EXAM',
  DELETE_EXAM = 'DELETE_EXAM',
  PUBLISH_EXAM = 'PUBLISH_EXAM',
  VIEW_EXAM_RESULTS = 'VIEW_EXAM_RESULTS',

  // Attempts
  START_ATTEMPT = 'START_ATTEMPT',
  SAVE_ANSWER = 'SAVE_ANSWER',
  SUBMIT_EXAM = 'SUBMIT_EXAM',
  VIEW_OWN_RESULT = 'VIEW_OWN_RESULT',

  // Grading
  REVIEW_AI_GRADE = 'REVIEW_AI_GRADE',
  OVERRIDE_GRADE = 'OVERRIDE_GRADE',
}
